import { Button } from "@/components/ui/Button";
import { createClient } from "@/lib/supabase/server";
import { ArrowUpRight, Camera, Heart, Mail, Play, Sparkles } from "lucide-react";
import Image from "next/image";
import Link from "next/link";

export async function PhotographerLanding() {
  const supabase = await createClient();
  const { data: events } = await supabase.from("events").select("id,slug,couple_name,wedding_date,location,portfolio_title,portfolio_description,event_type").eq("is_portfolio", true).eq("status", "live").order("wedding_date", { ascending: false });
  const ids = events?.map((event) => event.id) || [];
  const { data: media } = ids.length ? await supabase.from("event_media").select("event_id,public_url,type,created_at").in("event_id", ids).eq("approved", true).eq("type", "image").order("created_at") : { data: [] };
  const coverByEvent = new Map<string, string>();
  media?.forEach((item) => { if (!coverByEvent.has(item.event_id)) coverByEvent.set(item.event_id, item.public_url); });
  return <>
    <section className="relative isolate overflow-hidden px-4 pb-20 pt-36 sm:pb-28"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_18%_20%,#efd4e5,transparent_32%),radial-gradient(circle_at_85%_60%,#ded1ed,transparent_35%)]" /><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center"><div><p className="inline-flex items-center gap-2 rounded-full border border-primary/10 bg-white/80 px-4 py-2 text-xs font-semibold uppercase tracking-[0.17em] text-primary shadow-sm"><Sparkles className="h-4 w-4" /> Fotografia, która zostaje</p><h1 className="mt-7 font-serif text-5xl leading-[0.98] tracking-tight sm:text-7xl">Historie pełne<br /><em className="text-primary">prawdziwych emocji.</em></h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">Story Atelier tworzy reporterskie fotografie oraz cyfrowe opowieści o wyjątkowych dniach — od kameralnych przyjęć po wydarzenia, które zasługują na pamięć.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#portfolio"><Button size="lg" className="gap-2">Zobacz historie <ArrowUpRight className="h-4 w-4" /></Button></a><a href="#kontakt"><Button size="lg" variant="outline" className="gap-2"><Mail className="h-4 w-4" /> Zapytaj o termin</Button></a></div></div><div className="relative mx-auto w-full max-w-md"><div className="absolute -inset-5 -z-10 rotate-6 rounded-[3rem] bg-white/70" /><div className="aspect-[4/5] overflow-hidden rounded-[2.5rem] bg-gradient-to-br from-[#d89abc] to-[#7e608f] shadow-2xl shadow-primary/20">{coverByEvent.size > 0 && <Image src={[...coverByEvent.values()][0]} alt="Reportaż Story Atelier" fill className="object-cover" priority sizes="(max-width: 1024px) 100vw, 40vw" />}</div><div className="absolute -bottom-5 -left-5 rounded-2xl bg-white p-4 shadow-xl"><p className="font-serif text-xl">To Wasza historia.</p><p className="mt-1 text-xs text-muted-foreground">Uchwycona naturalnie</p></div></div></div></section>
    <section id="portfolio" className="mx-auto max-w-6xl px-4 py-20"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.17em] text-primary">Wybrane realizacje</p><h2 className="mt-3 font-serif text-4xl">Historie, do których się wraca</h2></div><p className="max-w-sm text-sm leading-6 text-muted-foreground">Każda realizacja jest opowiedziana inaczej — w rytmie ludzi, miejsca i emocji.</p></div>{events?.length ? <div className="mt-10 grid gap-6 md:grid-cols-2">{events.map((event, index) => <Link key={event.id} href={`/historia/${event.slug}`} className={`group relative min-h-[380px] overflow-hidden rounded-[2.25rem] bg-[#5e3c6d] shadow-lg ${index === 0 ? "md:col-span-2 md:min-h-[520px]" : ""}`}>{coverByEvent.get(event.id) && <Image src={coverByEvent.get(event.id)!} alt={event.portfolio_title || event.couple_name} fill className="object-cover transition duration-700 group-hover:scale-105" sizes={index === 0 ? "100vw" : "50vw"} />}<div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/10 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-7 text-white sm:p-9"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-white/70">{event.event_type === "wedding" ? "Reportaż ślubny" : "Event Story"}</p><h3 className="mt-3 font-serif text-4xl">{event.portfolio_title || event.couple_name}</h3><p className="mt-3 max-w-xl text-sm leading-6 text-white/80">{event.portfolio_description || event.location}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold">Otwórz historię <ArrowUpRight className="h-4 w-4" /></span></div></Link>)}</div> : <div className="mt-10 rounded-3xl border border-dashed border-border py-16 text-center text-muted-foreground">Portfolio jest właśnie przygotowywane.</div>}</section>
    <section className="bg-[#302036] px-4 py-20 text-white"><div className="mx-auto grid max-w-6xl gap-10 md:grid-cols-3"><div><Camera className="h-7 w-7 text-[#e8b5cf]" /><h3 className="mt-5 font-serif text-2xl">Reportaż, nie pozowanie</h3><p className="mt-3 text-sm leading-6 text-white/70">Prawdziwe gesty, spojrzenia i energia chwili — bez zatrzymywania wydarzenia.</p></div><div><Heart className="h-7 w-7 text-[#e8b5cf]" /><h3 className="mt-5 font-serif text-2xl">Od kameralnie do wielkiego formatu</h3><p className="mt-3 text-sm leading-6 text-white/70">Śluby, przyjęcia rodzinne, wydarzenia marek i spotkania, które mają znaczenie.</p></div><div><Play className="h-7 w-7 text-[#e8b5cf]" /><h3 className="mt-5 font-serif text-2xl">Historia także po wydarzeniu</h3><p className="mt-3 text-sm leading-6 text-white/70">Nowoczesny album, Event Story i prywatna pamiątka dla Twoich gości.</p></div></div></section>
    <section id="kontakt" className="mx-auto max-w-4xl px-4 py-24 text-center"><p className="text-sm font-semibold uppercase tracking-[0.17em] text-primary">Współpraca</p><h2 className="mt-3 font-serif text-5xl">Opowiedz mi o swoim wydarzeniu.</h2><p className="mx-auto mt-5 max-w-xl text-muted-foreground">Napisz, aby opowiedzieć o planowanym wydarzeniu i sprawdzić dostępność terminu.</p><Button size="lg" variant="outline" className="mt-8 gap-2"><Mail className="h-4 w-4" /> Kontakt wkrótce</Button></section>
  </>;
}
