"use client";

import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Textarea } from "@/components/ui/Textarea";
import { createClient } from "@/lib/supabase/client";
import { CheckCircle2, Image as ImageIcon, Loader2, MessageCircle, Upload } from "lucide-react";
import Link from "next/link";
import { FormEvent, useEffect, useRef, useState } from "react";

export default function EventSubmitPage({ params }: { params: Promise<{ slug: string }> }) {
  const supabase = createClient();
  const [slug, setSlug] = useState(""); const [eventId, setEventId] = useState(""); const [tab, setTab] = useState<"media" | "entry">("media"); const [file, setFile] = useState<File | null>(null); const [name, setName] = useState(""); const [caption, setCaption] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const input = useRef<HTMLInputElement>(null);
  useEffect(() => { params.then(({ slug }) => { setSlug(slug); supabase.from("events").select("id").eq("slug", slug).single().then(({ data }) => setEventId(data?.id || "")); }); }, [params]);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { if (!eventId) throw new Error("Wydarzenie nie jest dostępne."); if (tab === "entry") { const { error } = await supabase.from("event_guestbook_entries").insert({ event_id: eventId, author_name: name || "Gość", message, approved: false }); if (error) throw error; } else { if (!file) throw new Error("Wybierz zdjęcie lub film."); if (file.size > 250 * 1024 * 1024) throw new Error("Maksymalny rozmiar pliku to 250 MB."); const ext = file.name.split(".").pop() || "bin"; const path = `events/${eventId}/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`; const { error: uploadError } = await supabase.storage.from("event-media").upload(path, file); if (uploadError) throw uploadError; const { data: url } = supabase.storage.from("event-media").getPublicUrl(path); const { error: insertError } = await supabase.from("event_media").insert({ event_id: eventId, type: file.type.startsWith("video") ? "video" : "image", storage_path: path, public_url: url.publicUrl, caption, guest_name: name || null, approved: false }); if (insertError) throw insertError; } setNotice("Dziękujemy! Materiał czeka na zatwierdzenie przez fotografa."); setFile(null); setName(""); setCaption(""); setMessage(""); } catch (value: any) { setError(value.message || "Nie udało się przesłać wspomnienia."); } finally { setLoading(false); } }
  return <main className="flex min-h-screen items-center justify-center bg-[#fcf8fc] px-4 py-24"><section className="w-full max-w-xl rounded-[2rem] border border-white bg-white/85 p-7 shadow-xl sm:p-10"><Link href={`/e/${slug}`} className="text-sm text-muted-foreground">← Wróć do albumu</Link><h1 className="mt-5 font-serif text-4xl">Dodaj wspomnienie</h1><p className="mt-2 text-sm text-muted-foreground">Twoja treść pojawi się po akceptacji fotografa.</p><div className="mt-7 flex rounded-2xl bg-muted p-1"><button onClick={() => setTab("media")} className={`flex-1 rounded-xl px-3 py-2 text-sm font-semibold ${tab === "media" ? "bg-white shadow-sm" : "text-muted-foreground"}`}>Zdjęcie / film</button><button onClick={() => setTab("entry")} className={`flex-1 rounded-xl px-3 py-2 text-sm font-semibold ${tab === "entry" ? "bg-white shadow-sm" : "text-muted-foreground"}`}>Życzenia</button></div>{notice ? <div className="mt-7 text-center"><CheckCircle2 className="mx-auto h-14 w-14 text-green-500" /><p className="mt-3 font-medium">{notice}</p><Link href={`/e/${slug}`}><Button className="mt-5">Wróć do albumu</Button></Link></div> : <form onSubmit={submit} className="mt-6 space-y-4"><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Twoje imię (opcjonalnie)" />{tab === "media" ? <><button type="button" onClick={() => input.current?.click()} className="flex w-full flex-col items-center gap-2 rounded-2xl border-2 border-dashed border-border p-8 text-muted-foreground"><ImageIcon className="h-8 w-8" /><span className="text-sm font-medium">{file ? file.name : "Wybierz zdjęcie lub film"}</span><span className="text-xs">Maks. 250 MB</span></button><input ref={input} onChange={(e) => setFile(e.target.files?.[0] || null)} accept="image/*,video/*" type="file" className="hidden" /><Textarea value={caption} onChange={(e) => setCaption(e.target.value)} placeholder="Opis wspomnienia (opcjonalnie)" /></> : <Textarea required value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Napisz kilka słów dla Pary Młodej…" className="min-h-40" />}{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<Button disabled={loading} className="w-full gap-2">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : tab === "media" ? <Upload className="h-4 w-4" /> : <MessageCircle className="h-4 w-4" />}{loading ? "Wysyłanie…" : "Wyślij do akceptacji"}</Button></form>}</section></main>;
}
