"use client";

import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { createClient } from "@/lib/supabase/client";
import { ChevronDown, ChevronUp, Clock3, Loader2, Plus, Sparkles, Trash2 } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

type Chapter = { id: string; title: string; subtitle: string | null; chapter_type: string; sort_order: number; starts_at: string | null };
const presets = [
  { label: "Ślub i wesele", chapters: [["Przygotowania", "Pierwsze emocje przed ceremonią"], ["Goście przybywają", "Powitania i pierwsze uśmiechy"], ["Droga do ceremonii", "Wspólna podróż do ważnego momentu"], ["Ceremonia", "Przysięga i najważniejsze słowa"], ["Wyjście i gratulacje", "Pierwsze chwile już jako małżeństwo"], ["Powitanie na sali", "Toast, chleb i wspólne świętowanie"], ["Pierwszy taniec", "Moment tylko dla Nich"], ["Zabawa", "Parkiet, muzyka i emocje"], ["Podziękowania dla rodziców", "Wdzięczność, która zostaje"], ["Oczepiny", "Tradycja w nowej odsłonie"], ["Finał wieczoru", "Ostatnie kadry i wspomnienia"]] },
  { label: "Przyjęcie rodzinne", chapters: [["Powitanie gości", "Początek wspólnego świętowania"], ["Najważniejszy moment", "Ceremonia, toast lub prezentacja"], ["Wspólny stół", "Rozmowy, smaki i bliskość"], ["Życzenia", "Słowa od najbliższych"], ["Finał", "Pamiątka na lata"]] },
  { label: "Event firmowy", chapters: [["Przybycie gości", "Rejestracja i pierwsze rozmowy"], ["Otwarcie", "Start wydarzenia"], ["Program główny", "Prelekcje, premiery i inspiracje"], ["Networking", "Ludzie, rozmowy, współpraca"], ["Afterparty", "Energia po części oficjalnej"]] },
];

export function EventStoryManager({ eventId }: { eventId: string }) {
  const supabase = createClient(); const [chapters, setChapters] = useState<Chapter[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  async function load() { setLoading(true); const { data } = await supabase.from("event_story_chapters").select("id,title,subtitle,chapter_type,sort_order,starts_at").eq("event_id", eventId).order("sort_order"); setChapters((data as Chapter[]) || []); setLoading(false); }
  useEffect(() => { load(); }, [eventId]);
  async function add(title: string, subtitle: string | null, type = "custom") { setBusy(true); await supabase.from("event_story_chapters").insert({ event_id: eventId, title, subtitle, chapter_type: type, sort_order: chapters.length }); await load(); setBusy(false); }
  async function addPreset(preset: typeof presets[number]) { setBusy(true); await supabase.from("event_story_chapters").insert(preset.chapters.map(([title, subtitle], index) => ({ event_id: eventId, title, subtitle, chapter_type: "preset", sort_order: chapters.length + index }))); await load(); setBusy(false); }
  async function remove(id: string) { setBusy(true); await supabase.from("event_story_chapters").delete().eq("id", id); await load(); setBusy(false); }
  async function move(chapter: Chapter, direction: -1 | 1) { const target = chapters.find((item) => item.sort_order === chapter.sort_order + direction); if (!target) return; setBusy(true); await supabase.from("event_story_chapters").update({ sort_order: target.sort_order }).eq("id", chapter.id); await supabase.from("event_story_chapters").update({ sort_order: chapter.sort_order }).eq("id", target.id); await load(); setBusy(false); }
  function custom(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const title = String(form.get("title") || "").trim(); if (title) { add(title, String(form.get("subtitle") || "").trim() || null); event.currentTarget.reset(); } }
  return <section className="mt-6 rounded-3xl border border-border bg-white/75 p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-primary"><Sparkles className="h-4 w-4" /> Event Story</p><h2 className="mt-2 font-serif text-2xl">Opowiedz wydarzenie po kolei</h2><p className="mt-1 text-sm text-muted-foreground">Rozdziały zamieniają album w filmową historię — dla ślubów i każdego innego eventu.</p></div><Clock3 className="h-7 w-7 text-primary" /></div>{!chapters.length && <div className="mt-6 grid gap-3 sm:grid-cols-3">{presets.map((preset) => <Button key={preset.label} disabled={busy} variant="outline" onClick={() => addPreset(preset)} className="h-auto whitespace-normal py-4">{preset.label}</Button>)}</div>}<form onSubmit={custom} className="mt-6 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><Input required name="title" placeholder="Nazwa rozdziału" /><Input name="subtitle" placeholder="Krótki opis (opcjonalnie)" /><Button disabled={busy} className="gap-2"><Plus className="h-4 w-4" /> Dodaj</Button></form>{loading ? <Loader2 className="mx-auto my-8 h-6 w-6 animate-spin text-primary" /> : <div className="mt-5 space-y-2">{chapters.map((chapter, index) => <article key={chapter.id} className="flex items-center gap-3 rounded-2xl border border-border bg-white p-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-sm font-bold text-primary">{index + 1}</span><div className="min-w-0 flex-1"><p className="font-semibold">{chapter.title}</p>{chapter.subtitle && <p className="truncate text-xs text-muted-foreground">{chapter.subtitle}</p>}</div><div className="flex gap-1"><Button size="sm" variant="outline" disabled={busy || index === 0} onClick={() => move(chapter, -1)}><ChevronUp className="h-4 w-4" /></Button><Button size="sm" variant="outline" disabled={busy || index === chapters.length - 1} onClick={() => move(chapter, 1)}><ChevronDown className="h-4 w-4" /></Button><Button size="sm" variant="outline" disabled={busy} onClick={() => remove(chapter.id)} className="text-red-600"><Trash2 className="h-4 w-4" /></Button></div></article>)}</div>}</section>;
}
