"use client";

import { Button } from "@/components/ui/Button";
import { Camera, CheckCircle2, Loader2, RefreshCw, Send } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export default function KioskPage({ params }: { params: Promise<{ slug: string }> }) {
  const supabase = createClient();
  const videoRef = useRef<HTMLVideoElement>(null); const canvasRef = useRef<HTMLCanvasElement>(null);
  const [eventId, setEventId] = useState(""); const [coupleName, setCoupleName] = useState(""); const [stream, setStream] = useState<MediaStream | null>(null); const [photo, setPhoto] = useState<Blob | null>(null); const [guestName, setGuestName] = useState(""); const [status, setStatus] = useState<"loading" | "camera" | "preview" | "sending" | "done" | "unavailable">("loading"); const [error, setError] = useState("");

  useEffect(() => { params.then(async ({ slug }) => { const { data } = await supabase.from("events").select("id,couple_name,kiosk_enabled").eq("slug", slug).single(); if (!data?.kiosk_enabled) { setStatus("unavailable"); return; } setEventId(data.id); setCoupleName(data.couple_name); await startCamera(); }); return () => stream?.getTracks().forEach((track) => track.stop()); }, []);
  async function startCamera() { try { const nextStream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "user", width: { ideal: 1920 }, height: { ideal: 1080 } }, audio: false }); setStream(nextStream); if (videoRef.current) videoRef.current.srcObject = nextStream; setStatus("camera"); } catch { setError("Nie udało się uruchomić aparatu. Zezwól przeglądarce na użycie kamery."); setStatus("camera"); } }
  function capture() { const video = videoRef.current; const canvas = canvasRef.current; if (!video || !canvas) return; canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext("2d")?.drawImage(video, 0, 0); canvas.toBlob((blob) => { if (blob) { setPhoto(blob); stream?.getTracks().forEach((track) => track.stop()); setStatus("preview"); } }, "image/jpeg", 0.92); }
  async function submit() { if (!photo || !eventId) return; setStatus("sending"); const path = `events/${eventId}/kiosk-${Date.now()}.jpg`; const file = new File([photo], "kiosk-photo.jpg", { type: "image/jpeg" }); const { error: uploadError } = await supabase.storage.from("event-media").upload(path, file); if (uploadError) { setError(uploadError.message); setStatus("preview"); return; } const { data: url } = supabase.storage.from("event-media").getPublicUrl(path); const { error: insertError } = await supabase.from("event_media").insert({ event_id: eventId, type: "image", storage_path: path, public_url: url.publicUrl, guest_name: guestName || "Gość kiosku", approved: false }); if (insertError) { setError(insertError.message); setStatus("preview"); return; } setStatus("done"); window.setTimeout(reset, 6000); }
  function reset() { setPhoto(null); setGuestName(""); setError(""); startCamera(); }

  if (status === "unavailable") return <main className="flex min-h-screen items-center justify-center bg-[#201524] p-6 text-center text-white"><div><h1 className="font-serif text-4xl">Kiosk jest niedostępny</h1><p className="mt-3 text-white/70">Fotograf nie włączył jeszcze tego trybu.</p></div></main>;
  return <main className="min-h-screen bg-[#201524] p-5 text-white sm:p-8"><div className="mx-auto flex min-h-[calc(100vh-4rem)] max-w-6xl flex-col rounded-[2.5rem] bg-gradient-to-br from-[#432b4f] to-[#1c1220] p-6 shadow-2xl sm:p-10"><header className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-white/60">Fotobudka weselna</p><h1 className="mt-2 font-serif text-4xl sm:text-5xl">{coupleName || "Ładujemy wydarzenie…"}</h1><p className="mt-3 text-white/70">Zrób zdjęcie i zostaw je Parze Młodej.</p></header><div className="relative mx-auto mt-8 flex w-full max-w-3xl flex-1 items-center justify-center overflow-hidden rounded-[2rem] bg-black"><video ref={videoRef} autoPlay playsInline muted className={`max-h-[55vh] w-full object-cover ${status === "camera" ? "" : "hidden"}`} /><canvas ref={canvasRef} className="hidden" />{photo && <img src={URL.createObjectURL(photo)} alt="Podgląd zdjęcia" className="max-h-[55vh] w-full object-contain" />}{status === "loading" && <Loader2 className="h-10 w-10 animate-spin" />}</div>{status === "done" ? <div className="mt-7 text-center"><CheckCircle2 className="mx-auto h-16 w-16 text-green-400" /><h2 className="mt-3 font-serif text-3xl">Dziękujemy!</h2><p className="mt-2 text-white/70">Zdjęcie czeka na akceptację fotografa.</p><Button onClick={reset} className="mt-5">Zrób kolejne zdjęcie</Button></div> : status === "preview" ? <div className="mx-auto mt-6 flex w-full max-w-3xl flex-col gap-3 sm:flex-row"><input value={guestName} onChange={(e) => setGuestName(e.target.value)} placeholder="Twoje imię (opcjonalnie)" className="h-12 flex-1 rounded-xl border border-white/20 bg-white/10 px-4 text-white outline-none placeholder:text-white/50" /><Button onClick={submit} className="h-12 gap-2"><Send className="h-4 w-4" /> Wyślij zdjęcie</Button><Button onClick={reset} variant="outline" className="h-12 border-white/30 bg-transparent text-white hover:bg-white/10 hover:text-white"><RefreshCw className="h-4 w-4" /></Button></div> : <div className="mt-6 text-center"><Button onClick={capture} disabled={!stream} className="h-14 gap-2 rounded-full px-8 text-base"><Camera className="h-5 w-5" /> Zrób zdjęcie</Button>{error && <p className="mt-3 text-sm text-red-300">{error}</p>}</div>}</div></main>;
}
